In [5]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [9]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
d = np.zeros((3,3))
print(d)
e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# creating an identity matrix
g = np.eye(3,3)
print(g)

# creating an random matrix
random_matrix = np.random.random((2,3))
print(random_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.88350965 0.26802833 0.07897912]
 [0.80634879 0.04531256 0.57839412]]


In [18]:
# print every row of a column
print(random_matrix[ : ,2]) #slicing

[0.07897912 0.57839412]


In [22]:
random_matrix[1,1:3] = 1 #slicing
print(random_matrix)

[[0.88350965 0.26802833 0.07897912]
 [0.80634879 1.         1.        ]]


In [24]:
# set some rows annd col with any value
z = np.zeros((3,3),dtype=np.int64)
z[1,:] = 5
print(z)
z[:,2]=7
print(z)

[[0 0 0]
 [5 5 5]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [25]:
#datatypes
print(z.dtype)

int64


In [29]:
# mathematical operation
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#element wise addition,multiplication,division
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [33]:
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [36]:
# matrix multiplication / dot products
print(x)
print(y)
print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [38]:
# multiplication ( dot product) of vectors = scalar
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b)) # 30

30


In [39]:
print(a)

[1 2 3 4]


In [40]:
print(sum(a))

10


In [41]:
print(x)

[[1 2]
 [3 4]]


In [45]:
print(np.sum(x))
print(np.sum(x,axis=0)) # all elements of each row will be sum up for same column
print(np.sum(x,axis=1)) # all elements of each column will be sum up for same row

10
[4 6]
[3 7]


In [59]:
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 4 16 36 64]


In [89]:
a = np.stack((a,b),axis=0)

ValueError: all input arrays must have the same shape

In [90]:
print(a)

[[ 1  4  2 16]
 [ 3 36  4 64]]


In [95]:
a = a.reshape((8,1))
print(a)

[[ 1]
 [ 4]
 [ 2]
 [16]
 [ 3]
 [36]
 [ 4]
 [64]]


### Numpy Random Module

In [6]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [7]:
np.random.shuffle(a)
print(a)

[ 8 13  7 11 10 14  9  6  5 12]


In [8]:
a = np.random.rand(2,3)
print(a)

[[0.12842323 0.36861217 0.78902374]
 [0.08281295 0.98988372 0.74511821]]


In [9]:
a[0:,1:]

array([[0.36861217, 0.78902374],
       [0.98988372, 0.74511821]])

In [10]:
a = np.random.rand(3,3)

In [11]:
a

array([[0.9259439 , 0.49985023, 0.94168843],
       [0.23232729, 0.50115679, 0.44589191],
       [0.72935891, 0.36792889, 0.92915547]])

In [14]:
a[1:2,1:]

array([[0.50115679, 0.44589191]])